### ISSUE TITLE
PHP Version Mismatch

### ISSUE THREAD

**Issue by lfender6445** [ctrlaltdylan/MirrorMirror#5]
Following your instructions:

```
pi@raspberrypi /etc/nginx $ php -v
PHP 5.4.45-0+deb7u2 (cli) (built: Oct 27 2015 23:22:07)

pi@raspberrypi ~/projects/MirrorMirror $ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php >=5.5.9 but your PHP version (5.4.45) does not satisfy that requirement.
  Problem 2
    - illuminate/contracts v5.1.25 requires php >=5.5.9 -> your PHP version (5.4.45-0+deb7u2) or value of "config.platform.php" in composer.json does not satisfy that requirement.
    - illuminate/contracts v5.1.25 requires php >=5.5.9 -> your PHP version (5.4.45-0+deb7u2) or value of "config.platform.php" in composer.json does not satisfy that requirement.
    - Installation request for illuminate/contracts v5.1.25 -> satisfiable by illuminate/contracts[v5.1.25].

```

Not too familiar with version constraints for composer, but it appears the dependencies require a higher PHP version.

**Comment by AlhasanIQ** [comment]
just do `sudo apt-get update;sudo apt-get upgrade`

**Comment by ctrlaltdylan** [comment]
Making a list of things to update in the tutorial for after the holidays. Updating and upgrading is one of them. Happy new year all!

**Comment by lfender6445** [comment]
`apt-get update` won't work unless I have the repository including the higher version of PHP - unfortunately the [dotdeb repo](http://packages.dotdeb.org/dists/wheezy-php55/all/) doesn't support this version of PHP for my CPU, ARM7, one of the earlier pi's. I'll update this thread if I figure out how to build `php >= 5.5.9` using wheezy.

**Comment by lfender6445** [comment]
just out of curiosity, did you build this with pi2? wheezy or jessie?

**Comment by ctrlaltdylan** [comment]
Pi 2 with Jessie

**Comment by lfender6445** [comment]
upgrading to jessie fixed the PHP version, upgrade instructions here: https://raspberrypi.stackexchange.com/questions/27858/upgrade-to-raspbian-jessie, maybe make note of the OS requirements (for those still using pi1 wheezy) in readme when the holidays are over my oversight reading the original instructions
