### ISSUE TITLE
Where to choose weather location?

### ISSUE THREAD

**Issue by jbhitman** [ctrlaltdylan/MirrorMirror#6]
Sorry, I've looked through all of the config files, and I couldn't find where to change the weather location. Could you point me in the right direction?  thanks so much, and I'm sure my wife is going to love her MirrorMirror!

**Comment by AlhasanIQ** [comment]
/resources/views/mirror.blade.php
Line 56

**Comment by jbhitman** [comment]
Must have been the one file I didn't look in! :)  Thanks a bunch, works great!
